# -*- coding: utf-8 -*-
"""Answer Key Gen

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jDefk05lcRxO_8PmH0X6NWbNH71TpKaV

#***1) Extract Text from PDf***
"""

#Installing PyMuPDF
!pip install PyPDF2
!pip install pymupdf

#Install fpdf library
!pip install fpdf
#Installing PyMuPDF
!pip install PyPDF2
!pip install pymupdf
#Cohere API
!pip install cohere
!pip install --upgrade cohere

#Extracting text from pdf
import cohere
import fitz
doc = fitz.open('INd social - VI SA2 23-24.pdf')
text = ""
for page in doc:
 text+=page.get_text()

input = text
#print(text)
#input = "Write all answers. Do not skip any question.\n\n" + text
print(input)

"""## ***2) The extracted text needs to be sent in LLM API***

#*Cohere API (Response time comparatively Higher)*
"""

#Cohere API
!pip install cohere

!pip install --upgrade cohere

import cohere
co = cohere.Client('YOUR_API_KEY')

#Store the message you want to send into a variable

message = input

response = co.chat(
	message,
	model="command",
	temperature=0.9
)

answer = response.text
print(answer)

"""#***3) NOW WRITE THE TEXT INTO PDF FILE***"""

#Install fpdf library
!pip install fpdf

# Python program to create a pdf file

from fpdf import FPDF
#object of pdf
pdf = FPDF()

# Add a page
pdf.add_page()

# set style and size of font that you want in the pdf
pdf.set_font("Arial", size=15)


# create a cell
pdf.cell(200, 10, txt="Answer Key Generated (AZH Solutions):", ln=1, align='C')

# add another cell with the encoded text
#pdf.cell(100, 100, txt=answer, ln=1, align='L')
pdf.multi_cell(0, 5, 'text' + '\n' +answer)

# save the pdf with name .pdf
pdf.output("Answerkey1.pdf")

from fpdf import FPDF
#This is a function that takes text and file name as input and outputs the pdf with the text and filename.
def create_pdf(text):
    # Create a PDF object
    pdf = FPDF()

    # Add a page
    pdf.add_page()

    # Set style and size of font
    pdf.set_font("Arial", size=15)

    # Add a cell for the title
    pdf.cell(200, 10, txt="Answer Key Generated (AZH Solutions):", ln=1, align='C')

    # Add the text to the PDF
    pdf.multi_cell(0, 5, '_____' + '\n' +text)

    # Save the PDF
    pdf.output("Answerkey.pdf")
answer="Write this in PDF"
create_pdf(answer)